test_that("positions behaves as expected",{
  expect_identical(positions(M = mat, six_node = TRUE, level = "all", normalisation = "none"),positions_T_all_none)
  expect_identical(positions(M = mat, six_node = TRUE, level = "all", normalisation = "sum"), positions_T_all_sum)
  expect_identical(positions(M = mat, six_node = TRUE, level = "all", normalisation = "size class"), positions_T_all_sc)
  expect_identical(positions(M = mat, six_node = TRUE, level = "rows", normalisation = "none"), positions_T_rows_none)
  expect_identical(positions(M = mat, six_node = TRUE, level = "rows", normalisation = "sum"), positions_T_rows_sum)
  expect_identical(positions(M = mat, six_node = TRUE, level = "rows", normalisation = "size class"), positions_T_rows_sc)
  expect_identical(positions(M = mat, six_node = TRUE, level = "columns", normalisation = "none"), positions_T_columns_none)
  expect_identical(positions(M = mat, six_node = TRUE, level = "columns", normalisation = "sum"), positions_T_columns_sum)
  expect_identical(positions(M = mat, six_node = TRUE, level = "columns", normalisation = "size class"), positions_T_columns_sc)
  expect_identical(positions(M = mat, six_node = FALSE, level = "all", normalisation = "none"), positions_F_all_none)
  expect_identical(positions(M = mat, six_node = FALSE, level = "all", normalisation = "sum"), positions_F_all_sum)
  expect_identical(positions(M = mat, six_node = FALSE, level = "all", normalisation = "size class"), positions_F_all_sc)
  expect_identical(positions(M = mat, six_node = FALSE, level = "rows", normalisation = "none"), positions_F_rows_none)
  expect_identical(positions(M = mat, six_node = FALSE, level = "rows", normalisation = "sum"), positions_F_rows_sum)
  expect_identical(positions(M = mat, six_node = FALSE, level = "rows", normalisation = "size class"), positions_F_rows_sc)
  expect_identical(positions(M = mat, six_node = FALSE, level = "columns", normalisation = "none"), positions_F_columns_none)
  expect_identical(positions(M = mat, six_node = FALSE, level = "columns", normalisation = "sum"), positions_F_columns_sum)
  expect_identical(positions(M = mat, six_node = FALSE, level = "columns", normalisation = "size class"), positions_F_columns_sc)
})
