// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sd_m2
double sd_m2(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m2(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m2(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m3
double sd_m3(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m3(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m3(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m4
double sd_m4(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m4(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m4(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m5
double sd_m5(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m5(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m5(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m6
double sd_m6(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m6(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m6(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m7
double sd_m7(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m7(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m7(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m8
double sd_m8(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m8(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m8(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m9
double sd_m9(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m9(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m9(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m10
double sd_m10(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m10(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m10(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m11
double sd_m11(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m11(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m11(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m12
double sd_m12(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m12(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m12(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m13
double sd_m13(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m13(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m13(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m14
double sd_m14(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m14(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m14(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m15
double sd_m15(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m15(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m15(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m16
double sd_m16(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m16(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m16(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}
// sd_m17
double sd_m17(int NZ, int NP, NumericMatrix W, double m);
RcppExport SEXP _bmotif_sd_m17(SEXP NZSEXP, SEXP NPSEXP, SEXP WSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_m17(NZ, NP, W, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bmotif_sd_m2", (DL_FUNC) &_bmotif_sd_m2, 4},
    {"_bmotif_sd_m3", (DL_FUNC) &_bmotif_sd_m3, 4},
    {"_bmotif_sd_m4", (DL_FUNC) &_bmotif_sd_m4, 4},
    {"_bmotif_sd_m5", (DL_FUNC) &_bmotif_sd_m5, 4},
    {"_bmotif_sd_m6", (DL_FUNC) &_bmotif_sd_m6, 4},
    {"_bmotif_sd_m7", (DL_FUNC) &_bmotif_sd_m7, 4},
    {"_bmotif_sd_m8", (DL_FUNC) &_bmotif_sd_m8, 4},
    {"_bmotif_sd_m9", (DL_FUNC) &_bmotif_sd_m9, 4},
    {"_bmotif_sd_m10", (DL_FUNC) &_bmotif_sd_m10, 4},
    {"_bmotif_sd_m11", (DL_FUNC) &_bmotif_sd_m11, 4},
    {"_bmotif_sd_m12", (DL_FUNC) &_bmotif_sd_m12, 4},
    {"_bmotif_sd_m13", (DL_FUNC) &_bmotif_sd_m13, 4},
    {"_bmotif_sd_m14", (DL_FUNC) &_bmotif_sd_m14, 4},
    {"_bmotif_sd_m15", (DL_FUNC) &_bmotif_sd_m15, 4},
    {"_bmotif_sd_m16", (DL_FUNC) &_bmotif_sd_m16, 4},
    {"_bmotif_sd_m17", (DL_FUNC) &_bmotif_sd_m17, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bmotif(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
