# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sd_m2 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m2', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m3 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m3', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m4 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m4', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m5 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m5', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m6 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m6', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m7 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m7', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m8 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m8', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m9 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m9', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m10 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m10', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m11 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m11', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m12 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m12', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m13 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m13', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m14 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m14', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m15 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m15', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m16 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m16', PACKAGE = 'bmotif', NZ, NP, W, m)
}

sd_m17 <- function(NZ, NP, W, m) {
    .Call('_bmotif_sd_m17', PACKAGE = 'bmotif', NZ, NP, W, m)
}

